### ISSUE TITLE
Expose lua_status

### ISSUE THREAD

**Issue by notnotmelon** [JohnTheCoolingFan/factorio-mlua#6]
This library does not expose `lua_status`
There is a comment reading `// Disabled in Factorio lua`

However decompiling via hexrays shows that this function infact does exist.
![image](https://github.com/user-attachments/assets/495b5800-27fe-43fe-8bb9-e4be4f57ab98)

Additionally it is visible in the Factorio-Lua repo.
https://github.com/search?q=repo%3ARseding91%2FFactorio-Lua+lua_status&type=code

**Comment by notnotmelon** [comment]
Ref: https://github.com/JohnTheCoolingFan/factorio-mlua/blob/5538114f9bce7ea14664afe280ba0ffee3b8c207/factorio-mlua-sys/src/lua_factorio/lua.rs#L283C4-L283C31

**Comment by JohnTheCoolingFan** [comment]
Interesting. Must've missed it when commenting out crotoutines and other async stuff.

**Comment by JohnTheCoolingFan** [comment]
Alright, fixed version is now on crates.io, have fun!
